### ISSUE TITLE
Event Suggestion Button

### ISSUE THREAD

**Issue by nan2iz** [CS580-Thunderbird/study-hard-play-hard#10]
Create a radio button to allow user to select and view event suggestion list on their calendar

- [x] Create A Radio Button (The orange button) , you can select any colour that you like, We will talk about colour for our project later.

- [ ] Pull Events based on User's Preference Setting from back end // This will move to another issue

- [ ] Show Events on the Calendar // This will move to another issue

**Comment by wiehsingli** [comment]
Will this be on the calendar?

**Comment by nan2iz** [comment]
Yes, it's going to be on top of calendar.

Regarding the figure, the orange button is radio button for show/un-show events on the main calendar
![template01](https://cloud.githubusercontent.com/assets/17581141/22269551/b8d3e230-e240-11e6-8102-d5229e137588.PNG)

**Comment by nan2iz** [comment]
Closed by Diana
