### ISSUE TITLE
Add class for user setting -- Front end

### ISSUE THREAD

**Issue by nan2iz** [CS580-Thunderbird/study-hard-play-hard#12]
Please discuss who would like to take care this part. 
This feature is inside user setting, when they would like to add classes to their calendar.

- [x] - Retrieve data from back-end, when users are typing the class show the class list like search feature (There are example online)

- [x] - Return class back to back-end when user add the class to their schedule

Before you get class, you should pull data and put to database with this link "http://localhost:8080/getCppSchedule"
And you can get data from: /data/classes

And return GET method to backend /setting/add_class?code={class code}
Example "/setting/add_class?code=CS 580"

**Comment by nan2iz** [comment]
We may need to try out this.
Because there is big data, we may need to dump a Json file for this and put into static/data folder.

**Comment by wiehsingli** [comment]
doesn't the front end post the class code?

**Comment by nan2iz** [comment]
Sorry, I didn't understand your question.

**Comment by nan2iz** [comment]
Actually, it's GET method. Because back-end need only the class code, because we add data one by one.

**Comment by dlin345** [comment]
I used a GET method different from the original suggestion (/setting/add_class?code={class code}).  Instead I used GET method to JSON file.
