### ISSUE TITLE
Vote color for website theme

### ISSUE THREAD

**Issue by nan2iz** [CS580-Thunderbird/study-hard-play-hard#34]
Please put smile face on the color that you like

**Comment by nan2iz** [comment]
![image](https://cloud.githubusercontent.com/assets/17581141/22603745/7ba0d99e-e9fd-11e6-87df-7c5ce5c7f07e.png)

**Comment by nan2iz** [comment]
![image](https://cloud.githubusercontent.com/assets/17581141/22603784/a961a05c-e9fd-11e6-9263-f630d7c11775.png)

**Comment by nan2iz** [comment]
![image](https://cloud.githubusercontent.com/assets/17581141/22603794/b9b3496a-e9fd-11e6-8fdd-6db7b7342b9b.png)

**Comment by wiehsingli** [comment]
I like the third one

**Comment by nan2iz** [comment]
Thanks for the votes. I also vote number three. So we select the third one.
See color reference from below link
https://github.com/CS580-Thunderbird/study-hard-play-hard/wiki/Color-References
