### ISSUE TITLE
Provide POST data to set organizer of events to backend

### ISSUE THREAD

**Issue by nan2iz** [CS580-Thunderbird/study-hard-play-hard#39]
This is from the user settng,
After user set the preference, you  should add POST method and send JSON data to backend.

![screen shot 2017-02-05 at 10 45 30 pm](https://cloud.githubusercontent.com/assets/17581141/22637126/f31ff650-ebf4-11e6-869f-fb80ef227c1e.png)

**Comment by nan2iz** [comment]
Sorry I was confused a little bit.
Basically, you have to provide string list back to back-end. 
The String list contain id of event organizer that user check the checkboxes. 

So create Json format and pass POST method to "/setting/add_org"

Example
http://stackoverflow.com/questions/34789357/how-to-pass-liststring-in-post-method-using-spring-mvc

**Comment by wiehsingli** [comment]
can you check if I have set up POST correctly on back end?

**Comment by nan2iz** [comment]
Sorry, I didn't provide you accurate example.

You have to pass parameters to backend with JSON object. And backend will retrieve data with 
RequestBody method.

You have to request POST method in oder to private JSON object to back-end side.
Example:
http://stackoverflow.com/questions/30989391/angularjs-passing-complex-json-data-using-http-post

**Comment by nan2iz** [comment]
The Json should look like:
{"preferSet" : ["1","2"]}

**Comment by wiehsingli** [comment]
the 1 and 2 are the are different event preferences?

**Comment by nan2iz** [comment]
The numbers that represent event ID. The IDs are from "data/organizers"

**Comment by wiehsingli** [comment]
added post resembling the example.

**Comment by nan2iz** [comment]
Thanks for the update, btw I think you used the wrong button ("SEARCH CLUB FROM FACEBOOK PAGES") to pass the parameters.
I think we should create save button for save the setting. Or we can change the "Serch Club" button to be "Save" for now. And then when I finish "Search club from FB" feature, so we just add this button back.

![01_01](https://cloud.githubusercontent.com/assets/17581141/23180855/b5b0cbde-f827-11e6-9731-d5900c595bbc.PNG)

**Comment by nan2iz** [comment]
Please clean up the console and change button to be "save" instead of "Search Club From Facebook Pages" and then you can close this issue.
