### ISSUE TITLE
Add classes from user setting to calendar

### ISSUE THREAD

**Issue by nan2iz** [CS580-Thunderbird/study-hard-play-hard#41]

**Comment by nan2iz** [comment]
Hi Diana,
Here is some example

http://angular-ui.github.io/ui-calendar/


I will provide class data from user setting soon. 

![screen shot 2017-02-24 at 12 08 25 pm](https://cloud.githubusercontent.com/assets/17581141/23319084/020a1422-fa8a-11e6-9ab5-c9340dbcf516.png)

**Comment by nan2iz** [comment]
I'm not sure you finish this feature yet.
In my opinion: regarding the first design, i kind of want it to show the actual data on the calendar without requiring user to click on the calendar.

May you also add this feature ?

**Comment by dlin345** [comment]
I'm having trouble figuring out where the code is for adding each event to the calendar, so I can't inject the event name yet.  Since we're using bootstrap's calendar, I need to find out how to make changes to the code.

**Comment by nan2iz** [comment]
here is full example:
is the one that u r looking for ? 
https://mattlewis92.github.io/angular-bootstrap-calendar/#!?example=kitchen-sink

**Comment by nan2iz** [comment]
btw, the current example didn't provide feature to show details on the calendar, we need to apply change on the current code.
