### ISSUE TITLE
Make the pre-page.html to be responsive page

### ISSUE THREAD

**Issue by nan2iz** [CS580-Thunderbird/study-hard-play-hard#48]
Please make the pre-page.html to be more responsive to different type of screen. 

Recommendation technique: bootstrap. 
Btw, you also can apply other techniques as well.

If you have any question, please let me know. Thank you.

**Comment by dlin345** [comment]
Can you double check if this is correct?  I tested by changing the window size on my browser but I want to make sure it works for other people too.

**Comment by nan2iz** [comment]
It looks good on my devices. Thanks.
