### ISSUE TITLE
Null Obj in back-end side for "/setting/add_org"

### ISSUE THREAD

**Issue by nan2iz** [CS580-Thunderbird/study-hard-play-hard#51]
Can't read json for preferOrg list from front-end

**Comment by wiehsingli** [comment]
Does the object name have to be called preferOrg?

**Comment by nan2iz** [comment]
Oh actually it's preferSet.

May you check that front-end side actually send the object with json format or array ?

**Comment by wiehsingli** [comment]
I posted the object itself which should be json.  Do just need the array itself?

**Comment by nan2iz** [comment]
I need Json. Let me check on back-end side again.

**Comment by wiehsingli** [comment]
I tried just passing the array, i get a bad request, 400, error
