### ISSUE TITLE
Add "Add New Event" feature when click on the date

### ISSUE THREAD

**Issue by nan2iz** [CS580-Thunderbird/study-hard-play-hard#58]

**Comment by kushal-patel** [comment]
I'm still working on opening up the "Add Sched" tab of the userSettings and passing it the date of the day . But this should open up the userSettings.

**Comment by nan2iz** [comment]
ok

**Comment by nan2iz** [comment]
can you make it to be double click instead of one click ? Thanks.

**Comment by kushal-patel** [comment]
Ok I'll try to make it work on double click. I wasn't able to find a way to make it work on double click in the API documentation but I'll look into it.

**Comment by nan2iz** [comment]
Change to be click on Date. Diana will help on this.
