### ISSUE TITLE
User Setting Front-End

### ISSUE THREAD

**Issue by nan2iz** [CS580-Thunderbird/study-hard-play-hard#7]
Pop-Up setting button,  Please make sure it's on point.
I will break down tasks under this setting button with other issues.
![user-setting](https://cloud.githubusercontent.com/assets/17581141/22046650/ef356dae-dcd6-11e6-8763-345af89bd923.PNG)

**Comment by nan2iz** [comment]
Thank you for the update. I already checked your code, it's really nice template.

I wish to add more details about "insert work schedule/others" part. I hope, it's not too much. We can separate to another issue, if you like. 

![aday](https://cloud.githubusercontent.com/assets/17581141/22274055/0e58b466-e259-11e6-8c06-9a7ca02ed015.PNG)
![custom](https://cloud.githubusercontent.com/assets/17581141/22274054/0e571a84-e259-11e6-994f-5739fc597fb6.PNG)
![periodtime](https://cloud.githubusercontent.com/assets/17581141/22274056/0e5a4cc2-e259-11e6-81d9-0576b5643040.PNG)



P.S. If you have another design idea, please feel free to let me know. And please feel free to correct my English as well. Thank you very much. 
P.S. I forgot to add "Custom" and "Title" in Period Time picture.
P.S. Please take your time.
FYI: If you like to get free icons, this is really good website for icons [font awsome](http://fontawesome.io/icons/)

**Comment by nan2iz** [comment]
Another good example for design the selection for custom menu
![](https://www.theinternetpatrol.com/google-calendar-repeating-event-pop-up-20120515-134609.jpg)

**Comment by wiehsingli** [comment]
Its a rough draft. I plan to change it using angular.

**Comment by nan2iz** [comment]
Closed by Wilson
